//
// Created by lasovar on 7/28/26.
//

// GENERATED BY CLAUD, EDITED BY ME (@lasovar)
#pragma once

// HashMap<Key, T, Hash, KeyEqual> ----------------------------------------------------
//
// A move-only, clone-able wrapper around ankerl::unordered_dense::pmr::map that gives
// it the same "invalid allocator by default, no allocation until first real use"
// contract as Vec/String -- something the library itself can't do on its own.
//
// Root cause (verified against the actual source, not guessed): ankerl's table()
// default constructor delegates to table(0), and the bucket_count==0 path
// unconditionally calls allocate_buckets_from_shift(), which reserves its initial 4
// buckets right there -- before any insert. Confirmed empirically: constructing
// ankerl::unordered_dense::pmr::map<K,V> against a counting resource shows 1
// allocation before a single insert happens. So HashMap(&GetInvalidAllocator())
// would assert on construction, not on first use, if we just held the table
// directly the way Vec holds its buffer.
//
// Fix: don't construct the underlying table until it's actually touched. It's held
// in a `mutable std::optional`, materialized (bound to the real resource) by
// EnsureBound() on first access -- const methods can trigger this too (logical
// constness).
//
// Contract: only side-effect-free metadata (empty(), size(), get_allocator()) skips
// binding; everything else -- including read-only find()/contains(), not just
// mutators -- binds on first call. This is deliberately simpler than trying to make
// find() on a never-touched map return a real "not found" without materializing:
// that would need comparing a sentinel iterator against a genuinely bound table's
// end(), which relies on singular/default-constructed-iterator comparison behavior
// that isn't guaranteed portable across MSVC/Clang/GCC's std::vector::iterator
// implementations. So: construction never allocates, but the very first real query
// (even read-only) does, exactly once -- matching what the underlying ankerl table
// needs anyway once you're genuinely using it.
//
// This assumes the same AllocatorType/GetAllocator() pattern as Vec/String; delete
// the AllocatorType overloads if you don't have that.
//
// Scope: this wraps the common operations (insert/emplace/try_emplace, find/at/
// operator[]/contains/count, erase, iteration, clear/reserve). It does not re-derive
// ankerl's full surface (transparent lookup overloads, bucket introspection, rehash
// tuning, etc.) -- call raw() to get a reference to the real
// ankerl::unordered_dense::map for anything not covered here; raw() also binds first,
// so it's always safe to use even on a fresh HashMap.

#include "ankerl/unordered_dense.h"
#include "Quelos/Core/Allocators.hpp"
#include "Quelos/Core/AllocatorType.hpp"

#include "Pair.hpp"

#include <cassert>
#include <memory_resource>
#include <optional>
#include <utility>

#include "Optional.hpp"

namespace Quelos {
    template <typename Key, typename T, typename Hash = ankerl::unordered_dense::hash<Key>, typename KeyEqual =
              std::equal_to<Key>>
    class HashMap {
    public:
        using TableType = ankerl::unordered_dense::pmr::map<Key, T, Hash, KeyEqual>;
        using key_type = Key;
        using mapped_type = T;
        using value_type = typename TableType::value_type;
        using iterator = typename TableType::iterator;
        using const_iterator = typename TableType::const_iterator;
        using allocator_type = typename TableType::allocator_type;

        explicit HashMap() noexcept
            : m_Resource(&GetInvalidAllocator()) {}

        explicit HashMap(std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()) {}

        HashMap(const std::size_t buckets, std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()), m_Table(TableType(buckets, m_Resource)) {}

        HashMap(const std::size_t buckets, const AllocatorType allocatorType) noexcept
            : HashMap(buckets, GetAllocator(allocatorType)) {}

        HashMap(std::initializer_list<typename TableType::value_type> ilist, std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()), m_Table(TableType(ilist, m_Resource)) {}

        HashMap(std::initializer_list<typename TableType::value_type> ilist, const AllocatorType allocatorType) noexcept
            : HashMap(ilist, GetAllocator(allocatorType)) {}

        explicit HashMap(const AllocatorType allocatorType) noexcept : m_Resource(GetAllocator(allocatorType)) {}

        HashMap(const HashMap&) = delete;
        HashMap& operator=(const HashMap&) = delete;
        HashMap(HashMap&&) noexcept = default;
        HashMap& operator=(HashMap&&) noexcept = default;
        HashMap(HashMap&& other, allocator_type allocator) noexcept
            : m_Resource(allocator.resource()), m_Table(TableType(std::move(other.m_Table.value()), allocator)) {}

        void init(std::pmr::memory_resource* resource) {
            m_Resource = resource;
            EnsureBound();
        }

        void init(const AllocatorType allocatorType) {
            init(GetAllocator(allocatorType));
        }

        void init(allocator_type allocator) {
            init(allocator.resource());
        }

        [[nodiscard]] HashMap clone(std::pmr::memory_resource* resource) const {
            HashMap result(resource != nullptr ? resource : m_Resource);
            if (m_Table.has_value()) {
                result.EnsureBound();
                result.m_Table->reserve(m_Table->size());
                for (auto const& kv : *m_Table) {
                    result.m_Table->emplace(kv.first, kv.second);
                }
            }
            return result;
        }

        [[nodiscard]] HashMap clone(const AllocatorType allocatorType) const {
            return clone(GetAllocator(allocatorType));
        }

        [[nodiscard]] std::pmr::memory_resource* get_allocator() const noexcept { return m_Resource; }

        // Escape hatch for anything not wrapped below. Binds first, so always valid.
        [[nodiscard]] TableType& raw() {
            EnsureBound();
            return *m_Table;
        }

        [[nodiscard]] const TableType& raw() const {
            EnsureBound();
            return *m_Table;
        }

        [[nodiscard]] bool empty() const noexcept { return !m_Table.has_value() || m_Table->empty(); }
        [[nodiscard]] size_t size() const noexcept { return m_Table.has_value() ? m_Table->size() : 0; }

        void clear() noexcept {
            if (m_Table.has_value()) {
                m_Table->clear();
            }
        }

        void reserve(size_t count) {
            EnsureBound();
            m_Table->reserve(count);
        }

        template <typename... Args>
        Pair<iterator, bool> emplace(Args&&... args) {
            EnsureBound();
            return m_Table->emplace(std::forward<Args>(args)...);
        }

        template <typename... Args>
        Pair<iterator, bool> try_emplace(const Key& key, Args&&... args) {
            EnsureBound();
            return m_Table->try_emplace(key, std::forward<Args>(args)...);
        }

        template <typename... Args>
        Pair<iterator, bool> try_emplace(Key&& key, Args&&... args) {
            EnsureBound();
            return m_Table->try_emplace(std::move(key), std::forward<Args>(args)...);
        }

        Pair<iterator, bool> insert(const value_type& value) {
            EnsureBound();
            return m_Table->insert(value);
        }

        Pair<iterator, bool> insert(value_type&& value) {
            EnsureBound();
            return m_Table->insert(std::move(value));
        }

        [[nodiscard]] T& operator[](const Key& key) {
            EnsureBound();
            return (*m_Table)[key];
        }

        [[nodiscard]] T& operator[](Key&& key) {
            EnsureBound();
            return (*m_Table)[std::move(key)];
        }

        [[nodiscard]] T& at(const Key& key) {
            EnsureBound();
            return m_Table->at(key);
        }

        [[nodiscard]] const T& at(const Key& key) const {
            EnsureBound();
            return m_Table->at(key);
        }

        [[nodiscard]] iterator find(const Key& key) {
            EnsureBound();
            return m_Table->find(key);
        }

        [[nodiscard]] const_iterator find(const Key& key) const {
            EnsureBound();
            return m_Table->find(key);
        }

        [[nodiscard]] bool contains(const Key& key) const {
            EnsureBound();
            return m_Table->contains(key);
        }

        [[nodiscard]] size_t count(const Key& key) const {
            EnsureBound();
            return m_Table->count(key);
        }

        size_t erase(const Key& key) {
            EnsureBound();
            return m_Table->erase(key);
        }

        iterator erase(iterator it) {
            EnsureBound(); // caller could only have gotten `it` from an already-bound table
            return m_Table->erase(it);
        }

        // Iteration always binds -- see header comment on logical constness.
        [[nodiscard]] iterator begin() {
            EnsureBound();
            return m_Table->begin();
        }

        [[nodiscard]] iterator end() {
            EnsureBound();
            return m_Table->end();
        }

        [[nodiscard]] const_iterator begin() const {
            EnsureBound();
            return m_Table->begin();
        }

        [[nodiscard]] const_iterator end() const {
            EnsureBound();
            return m_Table->end();
        }

        void swap(HashMap& other) noexcept {
            using std::swap;
            swap(m_Table, other.m_Table);
            swap(m_Resource, other.m_Resource);
        }

        friend void swap(HashMap& a, HashMap& b) noexcept { a.swap(b); }

    private:
        void EnsureBound() const {
            if (!m_Table.has_value()) {
                m_Table.emplace(typename TableType::allocator_type(m_Resource));
            }
        }

        std::pmr::memory_resource* m_Resource;
        mutable Optional<TableType> m_Table; // unbound (None) until first real use
    };
} // namespace quelos
// std extensions /////////////////////////////////////////////////////////////

namespace std { // NOLINT(cert-dcl58-cpp)

    template <class Key, class T, class Hash, class KeyEqual, class Pred>
    // NOLINTNEXTLINE(cert-dcl58-cpp)
    auto erase_if(Quelos::HashMap<Key, T, Hash, KeyEqual>& map, Pred pred) -> std::size_t {
        using map_t = Quelos::HashMap<Key, T, Hash, KeyEqual>;

        // going back to front because erase() invalidates the end iterator
        auto const old_size = map.size();
        auto idx = old_size;
        while (idx) {
            --idx;
            auto it = map.begin() + static_cast<typename map_t::TableType::difference_type>(idx);
            if (pred(*it)) {
                map.erase(it);
            }
        }

        return old_size - map.size();
    }

} // namespace std
