//
// Created by lasovar on 7/28/26.
//

// GENERATED BY CLAUD, EDITED BY ME (@lasovar)

#pragma once

// HashSet<Key, Hash, KeyEqual> -----------------------------------------------------
//
// Same lazy-binding wrapper as HashMap, over ankerl::unordered_dense::pmr::set. See
// hash_map.hpp for the full rationale (verified root cause, contract, etc.) -- not
// repeated here.

#include "ankerl/unordered_dense.h"
#include "Quelos/Core/AllocatorType.hpp"

#include <memory_resource>
#include <optional>
#include <utility>

#include "Pair.hpp"

namespace Quelos {
    template <typename Key, typename Hash = ankerl::unordered_dense::hash<Key>, typename KeyEqual = std::equal_to<Key>>
    class HashSet {
    public:
        using TableType = ankerl::unordered_dense::pmr::set<Key, Hash, KeyEqual>;
        using key_type = Key;
        using value_type = typename TableType::value_type;
        using iterator = typename TableType::iterator;
        using const_iterator = typename TableType::const_iterator;
        using allocator_type = typename TableType::allocator_type;

        explicit HashSet() noexcept
            : m_Resource(&GetInvalidAllocator()) {}

        explicit HashSet(std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()) {}

        explicit HashSet(const AllocatorType allocatorType) noexcept : m_Resource(GetAllocator(allocatorType)) {}

        explicit HashSet(const allocator_type allocator) noexcept : m_Resource(allocator.resource()) {}

        HashSet(std::initializer_list<typename TableType::value_type> ilist, std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()), m_Table(TableType(ilist, m_Resource)) {}

        HashSet(std::initializer_list<typename TableType::value_type> ilist, AllocatorType allocatorType) noexcept
            : HashSet(ilist, GetAllocator(allocatorType)) {}

        HashSet(const HashSet&) = delete;
        HashSet& operator=(const HashSet&) = delete;
        HashSet(HashSet&&) noexcept = default;
        HashSet& operator=(HashSet&&) noexcept = default;

        HashSet(HashSet&& other, allocator_type allocator) noexcept
            : m_Resource(allocator.resource()), m_Table(TableType(std::move(other.m_Table.value()), allocator)) {}

        void init(std::pmr::memory_resource* resource) {
            m_Resource = resource;
            EnsureBound();
        }

        void init(const AllocatorType allocatorType) {
            init(GetAllocator(allocatorType));
        }

        void init(allocator_type allocator) {
            init(allocator.resource());
        }

        [[nodiscard]] HashSet clone(std::pmr::memory_resource* resource = nullptr) const {
            HashSet result(resource != nullptr ? resource : m_Resource);
            if (m_Table.has_value()) {
                result.EnsureBound();
                result.m_Table->reserve(m_Table->size());
                for (auto const& key : *m_Table) {
                    result.m_Table->emplace(key);
                }
            }
            return result;
        }

        [[nodiscard]] std::pmr::memory_resource* get_allocator() const noexcept { return m_Resource; }

        [[nodiscard]] TableType& raw() {
            EnsureBound();
            return *m_Table;
        }

        [[nodiscard]] const TableType& raw() const {
            EnsureBound();
            return *m_Table;
        }

        [[nodiscard]] bool empty() const noexcept { return !m_Table.has_value() || m_Table->empty(); }
        [[nodiscard]] size_t size() const noexcept { return m_Table.has_value() ? m_Table->size() : 0; }

        void clear() noexcept {
            if (m_Table.has_value()) {
                m_Table->clear();
            }
        }

        void reserve(size_t count) {
            EnsureBound();
            m_Table->reserve(count);
        }

        template <typename... Args>
        Pair<iterator, bool> emplace(Args&&... args) {
            EnsureBound();
            return m_Table->emplace(std::forward<Args>(args)...);
        }

        Pair<iterator, bool> insert(const Key& key) {
            EnsureBound();
            return m_Table->insert(key);
        }

        Pair<iterator, bool> insert(Key&& key) {
            EnsureBound();
            return m_Table->insert(std::move(key));
        }

        [[nodiscard]] iterator find(const Key& key) {
            EnsureBound();
            return m_Table->find(key);
        }

        [[nodiscard]] const_iterator find(const Key& key) const {
            EnsureBound();
            return m_Table->find(key);
        }

        [[nodiscard]] bool contains(const Key& key) const {
            EnsureBound();
            return m_Table->contains(key);
        }

        [[nodiscard]] size_t count(const Key& key) const {
            EnsureBound();
            return m_Table->count(key);
        }

        size_t erase(const Key& key) {
            EnsureBound();
            return m_Table->erase(key);
        }

        iterator erase(iterator it) {
            EnsureBound();
            return m_Table->erase(it);
        }

        [[nodiscard]] iterator begin() {
            EnsureBound();
            return m_Table->begin();
        }

        [[nodiscard]] iterator end() {
            EnsureBound();
            return m_Table->end();
        }

        [[nodiscard]] const_iterator begin() const {
            EnsureBound();
            return m_Table->begin();
        }

        [[nodiscard]] const_iterator end() const {
            EnsureBound();
            return m_Table->end();
        }

        void swap(HashSet& other) noexcept {
            using std::swap;
            swap(m_Table, other.m_Table);
            swap(m_Resource, other.m_Resource);
        }

        friend void swap(HashSet& a, HashSet& b) noexcept { a.swap(b); }

    private:
        void EnsureBound() const {
            if (!m_Table.has_value()) {
                m_Table.emplace(typename TableType::allocator_type(m_Resource));
            }
        }

        std::pmr::memory_resource* m_Resource;
        mutable std::optional<TableType> m_Table;
    };
} // namespace Quelos
