//
// Created by lasovar on 7/26/26.
//

#pragma once

// INITIAL VERSION GENERATED BY CLAUD - EDITED BY ME (@lasovar)

// String ---------------------------------------------------------------------------
//
// A move-only, null-terminated, UTF-8-agnostic byte string built on top of
// Vec<char, uint32_t>, so it reuses all of Vec's allocator/growth/move/clone
// machinery instead of re-deriving it.
//
// This file assumes your engine already provides, alongside Vec<T, SizeType>:
//   enum class AllocatorType { ... };
//   std::pmr::memory_resource* GetAllocator(AllocatorType type);
//   explicit Vec(const AllocatorType allocatorType) noexcept;   // ctor on Vec
// (exactly the constructor you showed). If your Vec doesn't have that
// AllocatorType constructor yet, either add it the same way you already did once,
// or just delete the AllocatorType overloads below and use the memory_resource*
// ones -- everything else is independent of that choice.
//
// Design notes:
//  - Not templated on SizeType: strings essentially never need >4B characters, and
//    a single canonical String type is simpler to pass around/compare/hash than a
//    family of them. If you eventually want a 64-bit variant, templatize then.
//  - Composition, not inheritance: Vec<char>'s public API (insert/resize/erase at
//    arbitrary positions) doesn't know about the null-terminator invariant, so it's
//    kept private. String exposes only text-shaped operations that maintain the
//    invariant themselves.
//  - Lazy materialization: a default-constructed (or moved-from, or clear()'d)
//    String holds an empty, unallocated Vec<char> -- no allocation, matching Vec's
//    own "no allocation until first use" behavior. c_str()/data() return a static
//    "" literal in that state rather than forcing an allocation just to have
//    something to point at. The first real mutation (append/assign/insert) lazily
//    pushes the '\0' terminator before doing anything else.
//  - No binary operator+: for a move-only pmr type, "a + b" would need to pick a
//    target allocator for the result with no natural default. Use .append()/+=
//    (grows in place, using this string's own resource) instead. If you want
//    out-of-place concatenation, write a small free function that takes the target
//    resource explicitly: `String Concat(const String&, const String&,
//    std::pmr::memory_resource*)`.
//  - at() mirrors whatever you're using on Vec (throwing std::out_of_range below,
//    matching the header you started from) -- swap it for the std::expected pattern
//    the same way you already did on Vec if you'd rather not throw.
//  - String s(0); is ambiguous (0 as a null pointer constant matches both the
//    memory_resource* and const char* constructors equally well) -- same flavor of
//    issue as Vec<T> v(0);. Use String s; instead.

#include <algorithm>
#include <cassert>
#include <compare>
#include <cstdint>
#include <functional>
#include <limits>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

#include "Vector.hpp"
#include "StringView.hpp"

namespace Quelos {
    template <typename SizeType>
    class StringT {
    public:
        using size_type = SizeType;
        static constexpr size_type npos = std::numeric_limits<size_type>::max();
        using allocator_type = VectorT<char, size_type>::allocator_type;

        // -- construction -----------------------------------------------------------

        explicit StringT() noexcept = default;

        explicit StringT(std::pmr::memory_resource* resource) noexcept
            : m_Data(resource) {}

        explicit StringT(allocator_type allocator) noexcept
            : m_Data(allocator) {}

        explicit StringT(const AllocatorType allocatorType) noexcept
            : m_Data(allocatorType) {}

        explicit StringT(const StringView sv, std::pmr::memory_resource* resource)
            : m_Data(resource)
        {
            assign(sv);
        }

        StringT(const StringView sv, const AllocatorType allocatorType)
            : m_Data(allocatorType)
        {
            assign(sv);
        }

        explicit StringT(const char* cstr, std::pmr::memory_resource* resource)
            : StringT(StringView(cstr), resource) {}

        StringT(const char* cstr, const AllocatorType allocatorType) : StringT(StringView(cstr), allocatorType) {}

        StringT& operator=(const StringT& other) {
            assign(other.view());
            return *this;
        }

        StringT(StringT&&) noexcept = default;
        StringT& operator=(StringT&&) noexcept = default;

        StringT(StringT&& other, std::pmr::memory_resource* memoryResource) noexcept
            : m_Data(std::move(other.m_Data), memoryResource) {}

        StringT(StringT&& other, allocator_type allocator) noexcept
            : StringT(std::move(other), allocator.resource()) {}

        StringT(StringT&& other, const AllocatorType allocatorType) noexcept
            : StringT(std::move(other), GetAllocator(allocatorType)) {}

        StringT& operator=(const StringView sv) {
            assign(sv);
            return *this;
        }

        [[nodiscard]] StringT clone(std::pmr::memory_resource* resource) const {
            return StringT(m_Data.clone(resource));
        }

        [[nodiscard]] StringT clone(allocator_type allocator) const {
            return StringT(m_Data.clone(allocator.resource()));
        }

        [[nodiscard]] StringT clone(const AllocatorType allocatorType) const {
            return StringT(m_Data.clone(allocatorType));
        }

        // -- allocator access ---------------------------------------------------------

        [[nodiscard]] std::pmr::memory_resource* get_allocator() const noexcept { return m_Data.get_allocator(); }

        // -- accessors ------------------------------------------------------------------

        [[nodiscard]] const char* c_str() const noexcept { return m_Data.empty() ? "" : m_Data.data(); }
        [[nodiscard]] const char* data() const noexcept { return c_str(); }

        [[nodiscard]] char* data() noexcept {
            EnsureMaterialized();
            return m_Data.data();
        }

        [[nodiscard]] size_type size() const noexcept { return m_Data.empty() ? 0 : m_Data.size() - 1; }
        [[nodiscard]] size_type length() const noexcept { return size(); }
        [[nodiscard]] bool empty() const noexcept { return size() == 0; }
        [[nodiscard]] size_type capacity() const noexcept { return m_Data.capacity() == 0 ? 0 : m_Data.capacity() - 1; }

        [[nodiscard]] StringView view() const noexcept { return {c_str(), size()}; }
        operator StringView() const noexcept { return view(); }

        [[nodiscard]] char& operator[](size_type index) noexcept {
            assert(index < size() && "String::operator[] index out of range");
            return m_Data[index];
        }

        [[nodiscard]] char operator[](size_type index) const noexcept {
            assert(index < size() && "String::operator[] index out of range");
            return m_Data[index];
        }

        [[nodiscard]] Expected<Ref<char>, IndexOutOfRange> at(size_type index) {
            if (index >= size()) {
                return Unexpected(IndexOutOfRange{ .Index = index, .Size = size() });
            }

            return m_Data[index];
        }

        [[nodiscard]] Expected<char, IndexOutOfRange> at(size_type index) const {
            if (index >= size()) {
                return Unexpected(IndexOutOfRange{ .Index = index, .Size = size() });
            }

            return m_Data[index];
        }

        [[nodiscard]] const char* begin() const noexcept { return c_str(); }
        [[nodiscard]] const char* end() const noexcept { return c_str() + size(); }

        [[nodiscard]] char* begin() noexcept {
            EnsureMaterialized();
            return m_Data.data();
        }

        [[nodiscard]] char* end() noexcept {
            EnsureMaterialized();
            return m_Data.data() + size();
        }

        // -- capacity / lifecycle ---------------------------------------------------------

        void reserve(size_type new_cap) { m_Data.reserve(static_cast<VectorT<char, size_type>::size_type>(new_cap) + 1); }
        void clear() noexcept { m_Data.clear(); }

        void swap(StringT& other) noexcept { m_Data.swap(other.m_Data); }
        friend void swap(StringT& lhs, StringT& rhs) noexcept { lhs.swap(rhs); }

        // -- mutation ------------------------------------------------------------------

        void assign(StringView sv) {
            m_Data.clear();
            if (sv.empty()) {
                return; // stay lazily unmaterialized if we had nothing allocated yet
            }
            m_Data.reserve(static_cast<size_type>(sv.size()) + 1);
            m_Data.insert(m_Data.end(), sv.begin(), sv.end());
            m_Data.push_back('\0');
        }

        StringT& append(StringView sv) {
            if (sv.empty()) {
                return *this;
            }
            EnsureMaterialized();
            m_Data.pop_back(); // drop the '\0'
            m_Data.insert(m_Data.end(), sv.begin(), sv.end());
            m_Data.push_back('\0');
            return *this;
        }

        StringT& append(char c) { return append(StringView(&c, 1)); }

        StringT& operator+=(StringView sv) { return append(sv); }
        StringT& operator+=(char c) { return append(c); }

        StringT& insert(size_type index, StringView sv) {
            assert(index <= size() && "String::insert index out of range");
            if (sv.empty()) {
                return *this;
            }
            EnsureMaterialized();
            m_Data.insert(m_Data.begin() + index, sv.begin(), sv.end());
            return *this;
        }

        StringT& erase(size_type index, size_type count = npos) {
            assert(index <= size() && "String::erase index out of range");
            size_type actual_count = count < size() - index ? count : size() - index;
            if (actual_count == 0) {
                return *this;
            }
            m_Data.erase(m_Data.begin() + index, m_Data.begin() + index + actual_count);
            return *this;
        }

        // -- slicing / search ------------------------------------------------------------

        // Zero-copy slice: valid only as long as this String outlives it and isn't mutated.
        [[nodiscard]] StringView substr_view(size_type index, size_type count = npos) const {
            assert(index <= size() && "String::substr_view index out of range");
            return view().substr(index, count);
        }

        // Owning slice: needs an explicit target allocator, same rationale as clone().
        [[nodiscard]] StringT substr(size_type index, size_type count, std::pmr::memory_resource* resource) const {
            return StringT(substr_view(index, count), resource);
        }

        [[nodiscard]] StringT substr(size_type index, size_type count, const AllocatorType allocatorType) const {
            return StringT(substr_view(index, count), allocatorType);
        }

        [[nodiscard]] size_type find(StringView needle, size_type from = 0) const noexcept {
            auto pos = view().find(needle, from);
            return pos == StringView::npos ? npos : static_cast<size_type>(pos);
        }

        [[nodiscard]] bool contains(StringView needle) const noexcept {
            return view().find(needle) != StringView::npos;
        }

        [[nodiscard]] bool starts_with(StringView prefix) const noexcept { return view().starts_with(prefix); }
        [[nodiscard]] bool ends_with(StringView suffix) const noexcept { return view().ends_with(suffix); }

        // -- comparisons ------------------------------------------------------------------

        [[nodiscard]] friend bool operator==(const StringT& lhs, const StringT& rhs) noexcept {
            return lhs.view() == rhs.view();
        }

        [[nodiscard]] friend bool operator==(const StringT& lhs, StringView rhs) noexcept {
            return lhs.view() == rhs;
        }

        [[nodiscard]] friend auto operator<=>(const StringT& lhs, const StringT& rhs) noexcept {
            return lhs.view() <=> rhs.view();
        }

        [[nodiscard]] friend auto operator<=>(const StringT& lhs, StringView rhs) noexcept {
            return lhs.view() <=> rhs;
        }

    private:
        explicit StringT(VectorT<char, size_type>&& data) noexcept : m_Data(std::move(data)) {}

        void EnsureMaterialized() {
            if (m_Data.empty()) {
                m_Data.push_back('\0');
            }
        }

        VectorT<char, size_type> m_Data; // invariant: either fully empty (unmaterialized) or
        // size() >= 1 with m_Data.back() == '\0'
    };

    // Transparent hash/equal for heterogeneous lookup in unordered_dense/std::unordered_map
    // keyed on String, without constructing a String just to look one up by
    // const char*/StringView
    struct TransparentStringHash {
        using is_transparent = void;

        [[nodiscard]] size_t operator()(StringView sv) const noexcept {
            return std::hash<StringView>{}(sv);
        }
    };

    struct TransparentStringEqual {
        using is_transparent = void;
        [[nodiscard]] bool operator()(StringView a, StringView b) const noexcept { return a == b; }
    };

    using String32 = StringT<uint32_t>;
    using String64 = StringT<uint64_t>;
    using String = String32;
} // namespace Quelos

template <typename SizeType>
struct std::hash<Quelos::StringT<SizeType>> {
    size_t operator()(const Quelos::StringT<SizeType>& s) const noexcept { return std::hash<Quelos::StringView>{}(s.view()); }
};
