#pragma once

// (Note: @Lasovar) GENERATED BY CLAUD, reviewed/edited by me

// Vec<T, SizeType>
//
// A move-only, std::vector-shaped container backed by a std::pmr::memory_resource*.
//
// Design notes:
//  - Storage is a raw contiguous T[] buffer; iterators are plain T*/const T*, so Vec
//    trivially satisfies std::contiguous_range and works with <ranges>, <algorithm>,
//    std::back_inserter, structured bindings over data(), etc. with zero extra glue.
//  - Vec does NOT own its std::pmr::memory_resource; it only holds a non-owning
//    pointer to one. If no resource is supplied, GetInvalidAllocator() is used, which
//    asserts on any actual allocation attempt. This is meant to catch "forgot to wire
//    up an allocator" bugs at the first allocation, rather than silently falling back
//    to some default global resource.
//  - Vec is move-only. There is no copy constructor / copy assignment. Deep copies are
//    always explicit via .clone([resource]), optionally cloning into a different
//    memory_resource than the original.
//  - Moving a Vec transfers buffer ownership (data/size/capacity) and adopts the
//    source's resource pointer (since that's the resource the stolen buffer was
//    actually allocated from). The moved-from Vec is left empty but keeps its OWN
//    original resource pointer unchanged, since that pointer is just a non-owning
//    reference to an externally-owned allocator (e.g. a frame arena) -- it is not
//    something the moved-from container needs to give up, and re-using the moved-from
//    Vec afterwards will simply allocate from that same resource again.
//  - SizeType is a template parameter defaulting to uint32_t to keep this cheap for
//    bulk gameplay/GPU-adjacent data; create a 64-bit alias where needed, e.g.:
//        template <typename T> using Vec64 = Vec<T, uint64_t>;
//
// Known limitations (accepted trade-offs for a solo-dev engine container, not bugs):
//  - Only a basic exception-safety guarantee is provided. Reallocation uses
//    std::move_if_noexcept, so if T's move constructor is noexcept (or T isn't
//    copyable), moves are used and a throw mid-reallocation can leave things in a
//    valid-but-unspecified state; there is no full rollback/transaction logic.
//  - Self-referential insert/push_back (e.g. v.push_back(v[0]) while v is at
//    capacity) is undefined behavior here, unlike std::vector post-DR: the reference
//    can dangle if a reallocation happens before it's read. Copy the value out first
//    if this pattern is needed.
//  - Vec<T> v(0); is technically ambiguous between the (memory_resource*) and
//    (size_type) constructors, since the integer literal 0 is also a null pointer
//    constant. Use Vec<T> v; or Vec<T> v(resource) instead of Vec<T> v(0);.
//
// Requires C++20 (concepts, std::construct_at/destroy_at, <=>, ranges-friendly
// iterators).

#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <expected>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <memory>
#include <memory_resource>
#include <stdexcept>
#include <type_traits>
#include <utility>

#include "Memory.hpp"
#include "Quelos/Core/AllocatorType.hpp"

namespace Quelos {
    template <typename T, typename SizeType = uint32_t>
        requires (std::is_unsigned_v<SizeType> && std::is_integral_v<SizeType>)
    class Vec {
    public:
        using value_type = T;
        using size_type = SizeType;
        using difference_type = std::ptrdiff_t;
        using reference = T&;
        using const_reference = const T&;
        using pointer = T*;
        using const_pointer = const T*;
        using iterator = T*;
        using const_iterator = const T*;
        using reverse_iterator = std::reverse_iterator<iterator>;
        using const_reverse_iterator = std::reverse_iterator<const_iterator>;

        // construction

        // Initializes m_Resource to &GetInvalidAllocator()
        Vec() noexcept {}

        explicit Vec(std::pmr::memory_resource* resource) noexcept
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator()) {}

        explicit Vec(const AllocatorType allocatorType) noexcept
            : m_Resource(GetAllocator(allocatorType)) {}

        explicit Vec(size_type count, std::pmr::memory_resource* resource)
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator())
        {
            resize(count);
        }

        explicit Vec(size_type count, const AllocatorType allocatorType)
            : Vec(count, GetAllocator(allocatorType))
        {
        }

        Vec(size_type count, const T& value, std::pmr::memory_resource* resource)
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator())
        {
            resize(count, value);
        }

        Vec(size_type count, const T& value, const AllocatorType allocatorType)
            : Vec(count, value, GetAllocator(allocatorType))
        {
        }

        template <typename InputIt>
            requires std::input_iterator<InputIt>
        Vec(InputIt first, InputIt last, std::pmr::memory_resource* resource)
            : m_Resource(resource != nullptr ? resource : &GetInvalidAllocator())
        {
            if constexpr (std::forward_iterator<InputIt>) {
                reserve(static_cast<size_type>(std::distance(first, last)));
            }

            for (; first != last; ++first) {
                emplace_back(*first);
            }
        }

        template <typename InputIt>
            requires std::input_iterator<InputIt>
        Vec(InputIt first, InputIt last, const AllocatorType allocatorType)
            : Vec(first, last, GetAllocator(allocatorType)) {}

        Vec(std::initializer_list<T> ilist, std::pmr::memory_resource* resource)
            : Vec(ilist.begin(), ilist.end(), resource) {}


        Vec(std::initializer_list<T> ilist, const AllocatorType allocatorType)
            : Vec(ilist.begin(), ilist.end(), GetAllocator(allocatorType)) {}

        Vec(const Vec&) = delete;
        Vec& operator=(const Vec&) = delete;

        Vec(Vec&& other) noexcept
            : m_Data(other.m_Data),
              m_Size(other.m_Size),
              m_Capacity(other.m_Capacity),
              m_Resource(other.m_Resource)
        {
            other.m_Data = nullptr;
            other.m_Size = 0;
            other.m_Capacity = 0;
            // other.m_Resource intentionally left unchanged - see header comment.
        }

        Vec& operator=(Vec&& other) noexcept {
            if (this == &other) {
                return *this;
            }

            memory::destroy_range(m_Data, m_Data + m_Size);
            DeallocateStorage(m_Data, m_Capacity);

            m_Data = other.m_Data;
            m_Size = other.m_Size;
            m_Capacity = other.m_Capacity;
            m_Resource = other.m_Resource; // adopt resource that actually owns the stolen buffer

            other.m_Data = nullptr;
            other.m_Size = 0;
            other.m_Capacity = 0;
            return *this;
        }

        Vec& operator=(std::initializer_list<T> ilist) {
            assign(ilist);
            return *this;
        }

        ~Vec() {
            memory::destroy_range(m_Data, m_Data + m_Size);
            DeallocateStorage(m_Data, m_Capacity);
        }

        // Explicit deep copy. Clones into `resource`, or into this Vec's own resource if
        // `resource` is nullptr.
        [[nodiscard]] Vec clone(std::pmr::memory_resource* resource) const {
            Vec result(resource != nullptr ? resource : m_Resource);
            result.reserve(m_Size);
            if constexpr (std::is_trivially_copyable_v<T>) {
                if (m_Size > 0) {
                    std::memcpy(result.m_Data, m_Data, static_cast<std::size_t>(m_Size) * sizeof(T));
                }
                result.m_Size = m_Size;
            }
            else {
                for (size_type i = 0; i < m_Size; ++i) {
                    result.emplace_back(m_Data[i]);
                }
            }

            return result;
        }

        [[nodiscard]] Vec clone(const AllocatorType allocatorType) const {
            return clone(GetAllocator(allocatorType));
        }

        // Allocator Access

        [[nodiscard]] std::pmr::memory_resource* get_allocator() const noexcept { return m_Resource; }

        // Iterators

        [[nodiscard]] iterator begin() noexcept { return m_Data; }
        [[nodiscard]] iterator end() noexcept { return m_Data + m_Size; }
        [[nodiscard]] const_iterator begin() const noexcept { return m_Data; }
        [[nodiscard]] const_iterator end() const noexcept { return m_Data + m_Size; }
        [[nodiscard]] const_iterator cbegin() const noexcept { return m_Data; }
        [[nodiscard]] const_iterator cend() const noexcept { return m_Data + m_Size; }

        [[nodiscard]] reverse_iterator rbegin() noexcept { return reverse_iterator(end()); }
        [[nodiscard]] reverse_iterator rend() noexcept { return reverse_iterator(begin()); }
        [[nodiscard]] const_reverse_iterator rbegin() const noexcept { return const_reverse_iterator(end()); }
        [[nodiscard]] const_reverse_iterator rend() const noexcept { return const_reverse_iterator(begin()); }
        [[nodiscard]] const_reverse_iterator crbegin() const noexcept { return const_reverse_iterator(end()); }
        [[nodiscard]] const_reverse_iterator crend() const noexcept { return const_reverse_iterator(begin()); }

        // size / capacity

        [[nodiscard]] bool empty() const noexcept { return m_Size == 0; }
        [[nodiscard]] size_type size() const noexcept { return m_Size; }
        [[nodiscard]] size_type capacity() const noexcept { return m_Capacity; }
        [[nodiscard]] static constexpr size_type max_size() noexcept { return std::numeric_limits<size_type>::max(); }

        void reserve(size_type new_cap) {
            if (new_cap > m_Capacity) {
                Reallocate(new_cap);
            }
        }

        void shrink_to_fit() {
            if (m_Size == m_Capacity) {
                return;
            }

            if (m_Size == 0) {
                DeallocateStorage(m_Data, m_Capacity);
                m_Data = nullptr;
                m_Capacity = 0;
                return;
            }

            T* new_data = AllocateStorage(m_Size);
            memory::relocate_range(new_data, m_Data, m_Size);
            DeallocateStorage(m_Data, m_Capacity);
            m_Data = new_data;
            m_Capacity = m_Size;
        }

        // Element Access

        [[nodiscard]] reference operator[](size_type index) noexcept {
            assert(index < m_Size && "Vec::operator[] index out of range!");
            return m_Data[index];
        }

        [[nodiscard]] const_reference operator[](size_type index) const noexcept {
            assert(index < m_Size && "Vec::operator[] index out of range!");
            return m_Data[index];
        }

        [[nodiscard]] std::expected<std::reference_wrapper<T>, std::out_of_range> at(size_type index) {
            if (index >= m_Size) {
                return std::out_of_range("Vec::at: index out of range");
            }

            return m_Data[index];
        }

        [[nodiscard]] std::expected<std::reference_wrapper<const T>, std::out_of_range> at(size_type index) const {
            if (index >= m_Size) {
                return std::out_of_range("Vec::at: index out of range");
            }

            return m_Data[index];
        }

        [[nodiscard]] reference front() noexcept {
            assert(m_Size > 0 && "Vec::front called on empty Vec");
            return m_Data[0];
        }

        [[nodiscard]] const_reference front() const noexcept {
            assert(m_Size > 0 && "Vec::front called on empty Vec");
            return m_Data[0];
        }

        [[nodiscard]] reference back() noexcept {
            assert(m_Size > 0 && "Vec::back called on empty Vec");
            return m_Data[m_Size - 1];
        }

        [[nodiscard]] const_reference back() const noexcept {
            assert(m_Size > 0 && "Vec::back called on empty Vec");
            return m_Data[m_Size - 1];
        }

        [[nodiscard]] pointer data() noexcept { return m_Data; }
        [[nodiscard]] const_pointer data() const noexcept { return m_Data; }

        // Modifiers

        void clear() noexcept {
            memory::destroy_range(m_Data, m_Data + m_Size);
            m_Size = 0;
        }

        template <typename... Args>
        reference emplace_back(Args&&... args) {
            if (m_Size == m_Capacity) {
                Reallocate(NextCapacity(m_Size + 1));
            }

            T* slot = m_Data + m_Size;
            std::construct_at(slot, std::forward<Args>(args)...);
            ++m_Size;
            return *slot;
        }

        reference push_back(const T& value) { return emplace_back(value); }
        reference push_back(T&& value) { return emplace_back(std::move(value)); }

        void pop_back() noexcept {
            assert(m_Size > 0 && "Vec::pop_back called on empty Vec");
            --m_Size;
            std::destroy_at(m_Data + m_Size);
        }

        void resize(size_type count) {
            if (count < m_Size) {
                memory::destroy_range(m_Data + count, m_Data + m_Size);
            }
            else if (count > m_Size) {
                reserve(count);
                for (size_type i = m_Size; i < count; ++i) {
                    std::construct_at(m_Data + i);
                }
            }

            m_Size = count;
        }

        void resize(size_type count, const T& value) {
            if (count < m_Size) {
                memory::destroy_range(m_Data + count, m_Data + m_Size);
            }
            else if (count > m_Size) {
                reserve(count);
                for (size_type i = m_Size; i < count; ++i) {
                    std::construct_at(m_Data + i, value);
                }
            }

            m_Size = count;
        }

        void assign(size_type count, const T& value) {
            clear();
            reserve(count);

            for (size_type i = 0; i < count; ++i) {
                std::construct_at(m_Data + i, value);
            }

            m_Size = count;
        }

        template <typename InputIt>
            requires std::input_iterator<InputIt>
        void assign(InputIt first, InputIt last) {
            clear();

            if constexpr (std::forward_iterator<InputIt>) {
                reserve(static_cast<size_type>(std::distance(first, last)));
            }

            for (; first != last; ++first) {
                emplace_back(*first);
            }
        }

        void assign(std::initializer_list<T> ilist) { assign(ilist.begin(), ilist.end()); }

        iterator insert(const_iterator pos, const T& value) { return emplace(pos, value); }
        iterator insert(const_iterator pos, T&& value) { return emplace(pos, std::move(value)); }

        iterator insert(const_iterator pos, size_type count, const T& value) {
            size_type index = static_cast<size_type>(pos - cbegin());
            if (count == 0) {
                return begin() + index;
            }

            MakeUninitializedGap(index, count);

            for (size_type i = 0; i < count; ++i) {
                std::construct_at(m_Data + index + i, value);
            }

            return begin() + index;
        }

        template <typename InputIt>
            requires std::input_iterator<InputIt>
        iterator insert(const_iterator pos, InputIt first, InputIt last) {
            size_type index = static_cast<size_type>(pos - cbegin());
            if constexpr (std::forward_iterator<InputIt>) {
                size_type count = static_cast<size_type>(std::distance(first, last));
                if (count == 0) {
                    return begin() + index;
                }

                MakeUninitializedGap(index, count);

                T* dst = m_Data + index;
                for (; first != last; ++first, ++dst) {
                    std::construct_at(dst, *first);
                }

                return begin() + index;
            }
            else {
                size_type i = index;
                for (; first != last; ++first, ++i) {
                    emplace(begin() + i, *first);
                }

                return begin() + index;
            }
        }

        iterator insert(const_iterator pos, std::initializer_list<T> ilist) {
            return insert(pos, ilist.begin(), ilist.end());
        }

        template <typename... Args>
        iterator emplace(const_iterator pos, Args&&... args) {
            size_type index = static_cast<size_type>(pos - cbegin());
            MakeUninitializedGap(index, 1);
            std::construct_at(m_Data + index, std::forward<Args>(args)...);
            return begin() + index;
        }

        iterator erase(const_iterator pos) { return erase(pos, pos + 1); }

        iterator erase(const_iterator first, const_iterator last) {
            size_type start = static_cast<size_type>(first - cbegin());
            size_type count = static_cast<size_type>(last - first);

            if (count == 0) {
                return begin() + start;
            }

            T* dst = m_Data + start;
            T* src = m_Data + start + count;
            size_type moved = m_Size - start - count;

            if constexpr (std::is_trivially_copyable_v<T>) {
                std::memmove(dst, src, static_cast<std::size_t>(moved) * sizeof(T));
            }
            else {
                for (size_type i = 0; i < moved; ++i) {
                    dst[i] = std::move(src[i]);
                }

                memory::destroy_range(m_Data + (m_Size - count), m_Data + m_Size);
            }

            m_Size -= count;
            return begin() + start;
        }

        template <typename Pred>
        size_type erase_if(Pred&& pred) {
            iterator out = begin();

            for (iterator it = begin(); it != end(); ++it) {
                if (!pred(*it)) {
                    if (out != it) {
                        *out = std::move(*it);
                    }

                    ++out;
                }
            }

            std::destroy(out, end());

            size_type removed = end() - out;

            m_Size -= removed;

            return removed;
        }

        template <std::ranges::input_range R>
        void append_range(R&& range) {
            if constexpr (std::ranges::sized_range<R>) {
                const size_type count = static_cast<size_type>(std::ranges::size(range));

                reserve(m_Size + count);

                if constexpr (std::is_trivially_copyable_v<T> &&
                    std::ranges::contiguous_range<R> &&
                    std::same_as<std::remove_cv_t<std::ranges::range_value_t<R>>, T>
                ) {
                    std::memcpy(m_Data + m_Size, std::ranges::data(range), count * sizeof(T));
                    m_Size += count;
                    return;
                }
            }

            for (auto&& value : range) {
                emplace_back(std::forward<decltype(value)>(value));
            }
        }

        void swap(Vec& other) noexcept {
            using std::swap;

            swap(m_Data, other.m_Data);
            swap(m_Size, other.m_Size);
            swap(m_Capacity, other.m_Capacity);
            swap(m_Resource, other.m_Resource);
        }

        friend void swap(Vec& lhs, Vec& rhs) noexcept { lhs.swap(rhs); }

        [[nodiscard]] friend bool operator==(const Vec& lhs, const Vec& rhs) {
            return std::equal(lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
        }

        [[nodiscard]] friend auto operator<=>(const Vec& lhs, const Vec& rhs) {
            return std::lexicographical_compare_three_way(lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
        }

    private:
        T* m_Data = nullptr;
        size_type m_Size = 0;
        size_type m_Capacity = 0;
        std::pmr::memory_resource* m_Resource = &GetInvalidAllocator();

        // internal helpers

        [[nodiscard]] T* AllocateStorage(size_type capacity) const {
            if (capacity == 0) {
                return nullptr;
            }
            void* raw = m_Resource->allocate(static_cast<std::size_t>(capacity) * sizeof(T), alignof(T));
            return static_cast<T*>(raw);
        }

        void DeallocateStorage(T* ptr, size_type capacity) noexcept {
            if (ptr != nullptr) {
                m_Resource->deallocate(ptr, static_cast<std::size_t>(capacity) * sizeof(T), alignof(T));
            }
        }

        [[nodiscard]] size_type NextCapacity(size_type requested) const noexcept {
            assert(requested <= max_size() && "Vec: requested capacity exceeds SizeType range");
            size_type doubled = m_Capacity > max_size() / 2 ? max_size() : static_cast<size_type>(m_Capacity * 2);
            if (doubled == 0) {
                doubled = 1;
            }

            return doubled > requested ? doubled : requested;
        }

        void Reallocate(size_type new_capacity) {
            T* new_data = AllocateStorage(new_capacity);
            memory::relocate_range(new_data, m_Data, m_Size);
            DeallocateStorage(m_Data, m_Capacity);
            m_Data = new_data;
            m_Capacity = new_capacity;
        }

        // Opens up a gap of `n` uninitialized slots at `index`, growing the buffer if
        // needed. Bumps m_size by n. Every slot in [index, index+n) is guaranteed to be
        // raw, un-constructed storage on return -- callers placement-construct into it.
        void MakeUninitializedGap(size_type index, size_type n) {
            if (n == 0) {
                return;
            }

            size_type new_size = m_Size + n;

            if (new_size > m_Capacity) {
                size_type new_capacity = NextCapacity(new_size);
                T* new_data = AllocateStorage(new_capacity);
                memory::relocate_range(new_data, m_Data, index);
                memory::relocate_range(new_data + index + n, m_Data + index, m_Size - index);
                DeallocateStorage(m_Data, m_Capacity);
                m_Data = new_data;
                m_Capacity = new_capacity;
            }
            else {
                size_type tail = m_Size - index;
                T* old_end = m_Data + m_Size;

                if constexpr (std::is_trivially_copyable_v<T>) {
                    std::memmove(m_Data + index + n, m_Data + index, static_cast<std::size_t>(tail) * sizeof(T));
                }
                else {
                    size_type to_construct = n < tail ? n : tail;
                    for (size_type i = 0; i < to_construct; ++i) {
                        std::construct_at(old_end + n - 1 - i, std::move(*(old_end - 1 - i)));
                    }

                    size_type to_assign = tail - to_construct;
                    for (size_type i = 0; i < to_assign; ++i) {
                        T* src = old_end - to_construct - 1 - i;
                        T* dst = src + n;
                        *dst = std::move(*src);
                    }

                    size_type alive_in_gap = tail < n ? tail : n;
                    memory::destroy_range(m_Data + index, m_Data + index + alive_in_gap);
                }
            }

            m_Size = new_size;
        }
    };

    template<typename T>
    Vec(std::initializer_list<T>) -> Vec<T>;

    template<typename T>
    Vec(std::initializer_list<T>, std::pmr::memory_resource*) -> Vec<T>;

    template<std::input_iterator It>
    Vec(It, It) -> Vec<std::iter_value_t<It>>;

    template<std::input_iterator It>
    Vec(It, It, std::pmr::memory_resource*) -> Vec<std::iter_value_t<It>>;

    template<std::ranges::input_range R>
    Vec(R&&) -> Vec<std::ranges::range_value_t<R>>;

    template<std::ranges::input_range R>
    Vec(R&&, std::pmr::memory_resource*) -> Vec<std::ranges::range_value_t<R>>;

    template <typename T, typename SizeType, typename Pred>
    typename Vec<T, SizeType>::size_type erase_if(Vec<T, SizeType>& vec, Pred&& predicate) {
        return vec.erase_if(std::forward<Pred>(predicate));
    }

    template <typename T, typename SizeType, typename U = T>
    typename Vec<T, SizeType>::size_type erase(Vec<T, SizeType>& vec, const U& value) {
        return vec.erase_if([&value](const T& x) { return x == value; });
    }
} // namespace Quelos

namespace std {
    using Quelos::erase;
    using Quelos::erase_if;
}
